### ISSUE TITLE
Conflict with conda-libmamba-solver

### ISSUE THREAD

**Issue by isuruf** [conda-forge/boa-feedstock#41]
`boa` depends on `mamba <0.22` which means `libmamba <0.22`, but `conda-libmamba-solver` depends on `libmamba>=0.22`.

cc @jaimergp, @jezdez, @wolfv

**Comment by jaimergp** [comment]
Oh yes, I saw this yesterday. It takes you down to a pre-libmambapy mamba :( 

I think `boa` works with 0.22 though. Can you confirm @wolfv? Maybe this is just a matter of repodata patching?

**Comment by wolfv** [comment]
I think we do need a new release of boa, unfortunately.

**Comment by wolfv** [comment]
I'll have a look later

**Comment by jezdez** [comment]
Thanks, I'm not sure how to solve this differently, if there is anything I can do @wolfv, please let me know. Maybe we should coordinate boa and conda-libmamba-solver releases somehow?

**Comment by wolfv** [comment]
Ideally we stop changing the `mamba` interface :)
Hopefully the next release will be the last one making major modifications for a long time.

**Comment by jezdez** [comment]
Gotcha, yeah, that seems like a good idea, would be really cool to make it a `1.0` so we can rely on it longer than usual, in boa and conda-libmamba-solver. For conda for example we open major release branches (e.g. `4.12.x`) for hot fixes and such, to be able to (finally again) do larger code changes like code deprecation etc.

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/boa-feedstock/pull/43
