### ISSUE TITLE
osx boa problems in ci, not sure if widespread

### ISSUE THREAD

**Issue by ngam** [conda-forge/boa-feedstock#48]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=556707&view=results

cc @wolfv @isuruf 

```
Installing ['conda-forge-ci-setup=3', 'conda-forge/label/lief_dev::py-lief', 'conda-forge/label/lief_dev::liblief'] and conda-build.
+ mamba install --update-specs --quiet --yes --channel conda-forge conda-build pip boa conda-forge-ci-setup=3 conda-forge/label/lief_dev::py-lief conda-forge/label/lief_dev::liblief
Encountered problems while solving:
  - package boa-0.10.0-pyha770c72_0 requires conda-build >=3.20,<3.22, but none of the providers can be installed

##[error]Bash exited with code '1'.
Finishing: Run OSX build

```

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by isuruf** [comment]
Should be fixed with https://github.com/conda-forge/boa-feedstock/pull/47

I've pulled the miniforge release for now.

**Comment by isuruf** [comment]
Removing https://github.com/conda-forge/jaxlib-feedstock/blob/main/conda-forge.yml#L11-L14 and rerender should fix this issue
