### ISSUE TITLE
Enable (resp. support) conda-build 3.26

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/boa-feedstock#75]
Conda-build 3.26 has a couple relevant fixes, but is currently suppressed by this feedstock
https://github.com/conda-forge/boa-feedstock/blob/0dfeb4882c719beb7dad3750035db4763b10f18a/recipe/meta.yaml#L26
which still causes conda-build 3.25 to be pulled in, in the context of a vanilla usage of the ci setup.

CC @conda-forge/boa
FYI @conda-forge/core

**Comment by chrisburr** [comment]
This might need to be dealt with first: https://github.com/mamba-org/mamba/issues/2715

**Comment by h-vetinari** [comment]
So I just wanted to open a PR to bump the mamba version cap here, but I saw the following comment in #73:
> @wolfv: I am sorry, I can't merge this because of a bug in mamba. I'll update the range once we've been able to test in the boa repository

There's no (easily found) metadata in the boa repo to indicate these bounds, but I then found https://github.com/mamba-org/boa/pull/351 and thus #72:
> @wolfv: Unfortunately this was on purpose since mamba 1.4.4 has a bug with the topological sorting. Should be fixed with 1.4.5 (released today).

So I'm not sure if I should open a PR (with `mamba >=1.4.5,<1.6`; or perhaps just with `!=1.4.3,!=1.4.4`?), or an issue in boa to test with new mamba/conda-build...

CC @wolfv @JohanMabille

**Comment by jaimergp** [comment]
We need mamba 1.5.0 for compatibility with conda 23.7.2 so I'd say let's test if 1.5.0 works with boa and if so, use that as the lower bound for simplicity?

**Comment by jaimergp** [comment]
Added suggestion in https://github.com/conda-forge/boa-feedstock/pull/74

**Comment by h-vetinari** [comment]
So #74 was merged last week and then marked [broken](https://github.com/conda-forge/admin-requests/pull/811).

@jaimergp, you said there
> boa 0.15.1 doesn't work with mamba 1.5.0

is that tracked anywhere? I tried following some of the links in #74, but I don't think https://github.com/conda/conda-build/issues/4991 is related, and https://github.com/mamba-org/boa/pull/367 hasn't seen an update since the merge.

**Comment by jaimergp** [comment]
The error is this one: https://github.com/conda-forge/staged-recipes/issues/23923

That `boa` version does work with 1.4.2 (and maybe others?), but not with 1.5.0. I didn't have more time to investigate the breakage and I am more focused on rolling out the conda-libmamba-solver integrations.

**Comment by h-vetinari** [comment]
Closing this as obsolete
