### ISSUE TITLE
Backport fix to unpin conda-build again

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/boa-feedstock#79]
The current meta.yaml does not have an upper bound for conda-build, but one was recently imposed by https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/657 due to https://github.com/mamba-org/boa/issues/392.

This keeps us from using the newest conda-build in CI (and thus some relevant fixes; c.f. https://github.com/conda-forge/conda-smithy/pull/1844). Looking at https://github.com/mamba-org/boa/pull/393, it shouldn't  be a big issue to backport this PR?

CC @jaimergp @mbargull

**Comment by mbargull** [comment]
We'd also want https://github.com/mamba-org/boa/pull/395 (or similar changes) for upcoming/future `conda`/`conda-build` version compat.

**Comment by jaimergp** [comment]
0.17.0 is coming (https://github.com/mamba-org/boa/pull/396) so I think we won't need this.
